feat: add node secure protocol options.
Deivu/Shoukaku pull request #29
Opened 2021-02-15 07:00 UTC by KagChi

2021-02-15 07:09 UTC, Deivu requested changes
Add the default value of secure on ShoukakuConstants, then move secure above the group?: in typings file, other than that, just add the missing docs and its good to go

2021-02-15 09:54 UTC, KagChi commented
is this correct?

2021-02-15 10:45 UTC, Allvaa commented
i think the option should be optional

2021-02-15 10:59 UTC, Deivu commented
I agree, since it gets merged to default constants value anyways, it could be optional instead as @Allvaa recommended

2021-02-15 13:17 UTC, Deivu commented on src/constants/ShoukakuConstants.js
> +    * @property {boolean} secure the protocols should secure or no.
just wrap secure with [] and ? on start of boolean to signify its optional on docs

2021-02-16 04:25 UTC, Deivu approved these changes

2021-02-16 04:25 UTC, Deivu commented
Seems good merging this thanks for the PR

2021-02-16 04:25 UTC, merged